name: "latest-release"

on: workflow_dispatch
# on:
#   schedule:
#     - cron:  '0 1 1,14 * *'

jobs:
  latest-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Build & test"
        run: |
          make dep
          make build-all
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            wapor-amd64-all.zip

